### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by nrempel** [InstantDomainSearch/instant-segment#12]
`cargo test`

```
dyld: Symbol not found: _PyBaseObject_Type
  Referenced from: /Users/nbrempel/Projects/instant-segment/target/debug/deps/instant_segment-9a57e3ec25b687df
  Expected in: flat namespace
 in /Users/nbrempel/Projects/instant-segment/target/debug/deps/instant_segment-9a57e3ec25b687df
error: test failed, to rerun pass '-p instant-segment-py --lib'
```

Seems related to https://github.com/PyO3/pyo3/issues/340

I am able to get tests to pass by adding `#[cfg(not(test))]` wherever we use #[pymethods]:

```rust
#[cfg(not(test))]
#[pymethods]
impl Search {
    /// Initialize an empty search buffer
    #[new]
    fn new() -> Self {
        Self {
            inner: instant_segment::Search::default(),
            cur: None,
        }
    }
}
```

**Comment by djc** [comment]
Yup, that's indeed the PyO3 issue. I don't think annotating all the impls with `#[cfg(not(test))]` is a good solution, so we'll need something else. For now, you can run `make test-python` to run the Python tests or `cargo t -p instant-segment --all-features` to run the Rust tests.

**Comment by nrempel** [comment]
Perfect, thanks. I'll add this to the documentation.
